"use strict";
const assert = require("node:assert/strict");
const { mergeReview, agentMergedReview } = require("../src/evidence-reactor-daemon.cjs");
const { validateCollection, validateAgentProposal, briefFingerprint, reviewableFingerprint } = require("../src/email-review-validator.cjs");
const reviewable = { object_type: "email_intel_brief", version: 1, brief_id: "email-intel-brief:primary", status: "candidate", source: { material_fingerprint: "e", revision: 1 }, title: "title", summary: "summary", claims: [], coverage: { available_entry_ids: [], cited_entry_ids: [], uncited_entry_ids: [] }, gaps: [], decision: null };
const brief = { ...reviewable, delivery: { status: "not_requested" } };
const first = mergeReview(null, brief, reviewable, null);
assert.deepEqual(validateCollection(first), first);
const action = { action_id: "human-1", kind: "submit_review", actor: "podsum.local-owner", target_via_id: brief.brief_id, target_fingerprint: "receipt", verdict: "approve", findings: ["ready"] };
const conflicted = mergeReview(first, brief, reviewable, action);
assert.equal(conflicted.conflicts.length, 0);
const disagree = { ...action, action_id: "human-2", verdict: "request_revision", findings: ["change"] };
const withConflict = mergeReview(conflicted, brief, reviewable, disagree);
assert.equal(withConflict.conflicts.length, 1);
const confirmedReviewable = { ...reviewable, status: "confirmed" };
const confirmed = mergeReview(withConflict, { ...brief, status: "confirmed" }, confirmedReviewable, null);
assert.ok(confirmed.reviews.every((review) => review.status === "resolved"));
const staleReviewable = { ...reviewable, source: { material_fingerprint: "other", revision: 2 } };
const stale = mergeReview(confirmed, { ...brief, source: { material_fingerprint: "other", revision: 2 } }, staleReviewable, null);
assert.ok(stale.reviews.some((review) => review.status === "superseded"));
const fingerprint = reviewableFingerprint(reviewable);
assert.equal(fingerprint, briefFingerprint(reviewable), "兼容 helper 必须保留 reviewable canonical hash");
assert.notEqual(fingerprint, reviewableFingerprint(brief), "Review identity 必须使用不含 delivery 的 reviewable fingerprint");
const proposal = { verdict: "approve", findings: ["The cited evidence supports the current candidate."] };
const agentResult = agentMergedReview(null, brief, reviewable, proposal, null);
const agentReview = agentResult.reviews[0];
assert.deepEqual(validateCollection(agentResult), agentResult, "kernel 必须输出最终严格 collection");
assert.equal(agentReview.reviewer_id, "agent:email-reviewer");
assert.equal(agentReview.brief_id, brief.brief_id, "kernel 必须绑定 current Brief");
assert.equal(agentReview.brief_fingerprint, fingerprint, "kernel 必须绑定 current reviewable backing");
assert.equal(agentReview.action_ref, `agent:${fingerprint}`);
const changedFinding = agentMergedReview(null, brief, reviewable, { ...proposal, findings: ["A differently worded finding."] }, null);
assert.equal(changedFinding.reviews[0].review_id, agentReview.review_id, "findings 随机性不得改变 stable ID");
assert.throws(() => validateAgentProposal({ ...proposal, review_id: "forged" }), /字段不精确/, "额外 authority 字段必须拒绝");
assert.throws(() => validateAgentProposal({ verdict: "approve", findings: [] }), /非空具体/, "空 findings 必须拒绝");
assert.throws(() => agentMergedReview(null, brief, reviewable, { ...proposal, status: "resolved" }, null), /字段不精确/, "Agent 不能提供 status 等 authority 字段");
console.log("#31 review proposal validator and deterministic commit verified");
