"use strict";
// #30: independent live five-contract black box.  No fake Agent, no Pixie.
const assert = require("node:assert/strict");
const { spawn, spawnSync } = require("node:child_process");
const fs = require("node:fs"); const http = require("node:http"); const net = require("node:net"); const os = require("node:os"); const path = require("node:path");
const prose = path.resolve(__dirname, ".."); const root = path.resolve(prose, "..", "..");
const python = process.env.PODSUM_PYTHON || path.join(os.homedir(), "Library/Application Support/Podsum/.venv/bin/python");
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "podsum-review-")); const project = path.join(temp, "project"); const state = path.join(temp, "state"); const downloads = path.join(temp, "downloads"); const ledger = path.join(downloads, "EmailReports/email-evidence-ledger.json"); const reviewStore = path.join(downloads, "EmailReports/email-review-actions.json");
const env = { ...process.env, OPENAI_AGENTS_DISABLE_TRACING: "1", PYTHONPATH: path.join(root, "outputs") }; const READY_MS = 300_000; const READ_MS = 30_000; const SEMANTIC_MS = 330_000;
let daemon; let workbench; let daemonPort; let daemonExit; let daemonOutput = ""; let workbenchOutput = "";
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function capture(child, setter) { child.stdout.on("data", (x) => setter(x)); child.stderr.on("data", (x) => setter(x)); }
function tail(old, chunk) { return (old + chunk.toString("utf8")).slice(-100_000); }
function port() { return new Promise((resolve, reject) => { const s = net.createServer(); s.once("error", reject); s.listen(0, "127.0.0.1", () => { const p = s.address().port; s.close(() => resolve(p)); }); }); }
function request(p, method, pathname, body, timeout) { return new Promise((resolve, reject) => { const text = body === undefined ? undefined : JSON.stringify(body); const q = http.request({ host: "127.0.0.1", port: p, method, path: pathname, timeout, agent: false, headers: text === undefined ? { connection: "close" } : { "content-type": "application/json", "content-length": Buffer.byteLength(text), connection: "close" } }, (r) => { let raw = ""; r.on("data", (x) => { raw += x; }); r.on("end", () => { try { resolve({ status: r.statusCode, body: JSON.parse(raw) }); } catch { reject(new Error(`${method} ${pathname} non-JSON: ${raw}`)); } }); }); q.on("timeout", () => q.destroy(new Error(`${method} ${pathname} timed out`))); q.on("error", (e) => reject(e)); if (text) q.write(text); q.end(); }); }
function alive() { if (daemonExit) throw new Error(`daemon exited: ${daemonExit}`); }
async function ready(p) { const end = Date.now() + READY_MS; while (Date.now() < end) { alive(); try { if ((await request(p, "GET", "/health", undefined, READ_MS)).status === 200) return; } catch {} await sleep(250); } throw new Error("daemon readiness exceeded 300 seconds"); }
async function stop(child) { if (!child || child.exitCode !== null) return; child.kill("SIGTERM"); await Promise.race([new Promise((r) => child.once("exit", r)), sleep(5000)]); if (child.exitCode === null) child.kill("SIGKILL"); }
function pack() { return { object_type: "email_evidence_pack", object_version: "1", status: "ready_for_summary", date: "2026-07-14", account: "sanitized@test", window: "daily", scan_limit: 1, raw_count: 1, possibly_truncated: false, items: [{ uid: "A", date: "2026-07-14", from: "sender@test", subject: "Launch", snippet: "Sanitized factual launch update", evidence: [] }] }; }
function ingress(file) { const r = spawnSync(python, [path.join(root, "outputs/email/evidence_ingress.py"), file, ledger, `http://127.0.0.1:${daemonPort}`], { cwd: root, env, encoding: "utf8", timeout: SEMANTIC_MS }); alive(); assert.equal(r.error, undefined, r.error?.message); assert.equal(r.status, 0, `${r.stdout}\n${r.stderr}`); return JSON.parse(r.stdout); }
async function get(pathname) { return request(daemonPort, "GET", pathname, undefined, READ_MS); }
async function diagnostics() { const one = async (p) => { try { return await get(p); } catch (e) { return { error: String(e) }; } }; console.error("#30 live review diagnostics:\n" + JSON.stringify({ receipts: await one("/receipts"), status: await one("/status"), brief: await one("/via/email-intel-brief"), review: await one("/via/email-review"), daemon_exit: daemonExit || null, daemon_stdout_stderr: daemonOutput || "(none)", workbench_stdout_stderr: workbenchOutput || "(none)" }, null, 2)); }
function receiptCount(receipts, node) { return receipts.body.receipts.filter((r) => r.node === node).length; }
function noSend(receipts) { return receipts.body.receipts.every((r) => !/send|deliver/i.test(r.node || "") && !Object.prototype.hasOwnProperty.call(r, "side_effect")); }
(async () => {
  assert.ok(process.env.OPENAI_API_KEY, "OPENAI_API_KEY is required"); assert.ok(fs.existsSync(python), `app venv missing: ${python}`);
  fs.mkdirSync(path.join(project, "src"), { recursive: true });
  for (const file of ["email-evidence-gateway.prose.md", "workbench-action-gateway.prose.md", "email-evidence-responsibility.prose.md", "email-intel-brief-responsibility.prose.md", "email-review-responsibility.prose.md"]) fs.copyFileSync(path.join(prose, "src", file), path.join(project, "src", file));
  daemonPort = await port(); daemon = spawn(process.execPath, [path.join(prose, "src/evidence-reactor-daemon.cjs"), "--contracts", path.join(project, "src"), "--state", state, "--ledger", ledger, "--review-store", reviewStore, "--delivery-mode", "file", "--delivery-outbox", path.join(temp, "outbox"), "--delivery-target", "fixture-file", "--port", String(daemonPort)], { cwd: project, env, stdio: ["ignore", "pipe", "pipe"] }); capture(daemon, (x) => { daemonOutput = tail(daemonOutput, x); }); daemon.once("exit", (code, signal) => { daemonExit = `code=${code}, signal=${signal}`; }); await ready(daemonPort);
  const fixture = path.join(temp, "pack.json"); fs.writeFileSync(fixture, JSON.stringify(pack())); ingress(fixture);
  let brief = await get("/via/email-intel-brief"); let review = await get("/via/email-review"); assert.equal(brief.status, 200); assert.equal(brief.body.status, "candidate"); assert.ok(brief.body.via_fingerprint); assert.equal(review.status, 200); const agent = review.body.reviews.find((r) => r.kind === "agent" && r.status === "submitted"); assert.ok(agent, "a real submitted semantic Agent review is required"); assert.ok(agent.findings.length && !agent.findings.every((x) => /^pending$/i.test(x)), "Agent findings must not be placeholder pending");
  let receipts = await get("/receipts"); for (const node of ["7R6QX8GZ3EW3S7PVJ9KQ6E2D4M", "email-review-responsibility"]) assert.ok(receipts.body.receipts.filter((r) => r.node === node).every((r) => r.wake?.source === "input"), `${node} must be input-driven`); const reviewAgentReceipt = receipts.body.receipts.filter((r) => r.node === "email-review-responsibility").find((r) => r.cost?.provider !== "deterministic"); assert.ok(reviewAgentReceipt && ((reviewAgentReceipt.cost.tokens?.fresh || 0) + (reviewAgentReceipt.cost.tokens?.reused || 0) > 0), "Review Agent cost fresh/reused must be non-zero");
  const wbPort = await port(); workbench = spawn(python, [path.join(root, "outputs/podsum_email_workbench.py"), "--root", downloads, "--date", "2026-07-14", "--port", String(wbPort), "--reactor-endpoint", `http://127.0.0.1:${daemonPort}`], { cwd: root, env, stdio: ["ignore", "pipe", "pipe"] }); capture(workbench, (x) => { workbenchOutput = tail(workbenchOutput, x); }); for (let i = 0; i < 100; i += 1) { try { if ((await request(wbPort, "GET", "/api/context", undefined, READ_MS)).status === 200) break; } catch {} await sleep(100); }
  const wbReviews = await request(wbPort, "GET", "/api/reviews", undefined, READ_MS); assert.equal(wbReviews.status, 200); assert.deepEqual(wbReviews.body.reviews, review.body); const page = await new Promise((resolve, reject) => http.get(`http://127.0.0.1:${wbPort}/`, (r) => { let s = ""; r.on("data", (x) => { s += x; }); r.on("end", () => resolve(s)); }).on("error", reject)); for (const id of ["reviewList", "reviewConflicts", "submitReviewForm", "revisionForm", "confirmBrief", "review-action-status"]) assert.ok(page.includes(id), `stable Review UI id missing: ${id}`); for (const id of ["review-list", "review-conflicts", "submit-review-form", "revision-form", "confirm-brief"]) assert.ok(page.includes(`data-testid=\"${id}\"`), `stable Review UI testid missing: ${id}`);
  const opposite = agent.verdict === "approve" ? "request_revision" : "approve"; const humanAction = { action_id: "human-opposite", kind: "submit_review", actor: "podsum.local-owner", verdict: opposite, findings: ["Human live conflict finding"] }; let action = await request(wbPort, "POST", "/api/review-actions", humanAction, SEMANTIC_MS); assert.equal(action.status, 200); review = await get("/via/email-review"); const human = review.body.reviews.find((r) => r.action_ref === "human-opposite"); assert.deepEqual({ kind: human.kind, verdict: human.verdict, findings: human.findings, status: human.status }, { kind: "human", verdict: opposite, findings: humanAction.findings, status: "submitted" }); assert.ok(review.body.conflicts.length, "opposite human verdict must be visible as conflict"); assert.ok(review.body.processed_action_ids.includes("human-opposite")); const humanMergeReceipt = (await get("/receipts")).body.receipts.filter((r) => r.node === "email-review-responsibility").at(-1); assert.equal(humanMergeReceipt.cost.provider, "deterministic"); assert.equal((humanMergeReceipt.cost.tokens.fresh || 0) + (humanMergeReceipt.cost.tokens.reused || 0), 0, "human merge cost must be zero");
  const bytes = fs.readFileSync(reviewStore); const beforeBriefReceipts = receiptCount(await get("/receipts"), "7R6QX8GZ3EW3S7PVJ9KQ6E2D4M"); const beforeReviewReceipts = receiptCount(await get("/receipts"), "email-review-responsibility"); brief = await get("/via/email-intel-brief"); for (const bad of [{ action_id: "agent-confirm", kind: "confirm_brief", actor: "agent:email-reviewer", target_via_id: brief.body.brief_id, target_fingerprint: brief.body.via_fingerprint }, { action_id: "stale-confirm", kind: "confirm_brief", actor: "podsum.local-owner", target_via_id: brief.body.brief_id, target_fingerprint: "stale" }]) assert.equal((await request(daemonPort, "POST", "/trigger/workbench-action", bad, SEMANTIC_MS)).status, 400); assert.deepEqual(fs.readFileSync(reviewStore), bytes); assert.equal(receiptCount(await get("/receipts"), "7R6QX8GZ3EW3S7PVJ9KQ6E2D4M"), beforeBriefReceipts); assert.equal(receiptCount(await get("/receipts"), "email-review-responsibility"), beforeReviewReceipts);
  const oldFingerprint = review.body.brief.brief_fingerprint; const revisionAction = { action_id: "revision-1", kind: "request_revision", actor: "podsum.local-owner", feedback: "Revise the launch framing with concrete evidence." }; action = await request(wbPort, "POST", "/api/review-actions", revisionAction, SEMANTIC_MS); assert.equal(action.status, 200); const revised = await get("/via/email-intel-brief"); review = await get("/via/email-review"); assert.equal(revised.body.status, "candidate"); assert.equal(revised.body.decision.last_action_id, "revision-1"); assert.notEqual(revised.body.via_fingerprint, oldFingerprint); assert.ok(review.body.reviews.some((r) => r.action_ref === "revision-1" && r.kind === "human" && r.verdict === "request_revision")); assert.ok(review.body.reviews.filter((r) => r.brief_fingerprint === oldFingerprint).every((r) => r.status === "superseded")); const newAgent = review.body.reviews.find((r) => r.brief_fingerprint === review.body.brief.brief_fingerprint && r.kind === "agent" && r.status === "submitted"); assert.ok(newAgent, "revised candidate needs real submitted Agent review");
  const confirm = { action_id: "confirm-1", kind: "confirm_brief", actor: "podsum.local-owner" }; action = await request(wbPort, "POST", "/api/review-actions", confirm, SEMANTIC_MS); assert.equal(action.status, 200); const confirmed = await get("/via/email-intel-brief"); review = await get("/via/email-review"); assert.equal(confirmed.body.status, "confirmed"); assert.equal(confirmed.body.decision.last_action_id, "confirm-1"); assert.ok(review.body.reviews.filter((r) => r.brief_fingerprint === review.body.brief.brief_fingerprint).every((r) => r.status !== "submitted")); receipts = await get("/receipts"); assert.ok(noSend(receipts), "review flow must have no send/delivery receipt or side effect");
  const reviewCount = review.body.reviews.length; const processedCount = review.body.processed_action_ids.length; const replay = { ...confirm, target_via_id: revised.body.brief_id, target_fingerprint: revised.body.via_fingerprint }; assert.equal((await request(daemonPort, "POST", "/trigger/workbench-action", replay, SEMANTIC_MS)).status, 200); review = await get("/via/email-review"); assert.equal(review.body.reviews.length, reviewCount); assert.equal(review.body.processed_action_ids.length, processedCount);
  await stop(daemon); daemon = undefined; daemonExit = undefined; daemonPort = await port(); daemon = spawn(process.execPath, [path.join(prose, "src/evidence-reactor-daemon.cjs"), "--contracts", path.join(project, "src"), "--state", state, "--ledger", ledger, "--review-store", reviewStore, "--delivery-mode", "file", "--delivery-outbox", path.join(temp, "outbox"), "--delivery-target", "fixture-file", "--port", String(daemonPort)], { cwd: project, env, stdio: ["ignore", "pipe", "pipe"] }); capture(daemon, (x) => { daemonOutput = tail(daemonOutput, x); }); daemon.once("exit", (code, signal) => { daemonExit = `code=${code}, signal=${signal}`; }); await ready(daemonPort); const restoredBrief = await get("/via/email-intel-brief"); const restoredReview = await get("/via/email-review"); assert.equal(restoredBrief.body.status, "confirmed"); assert.deepEqual(restoredReview.body.processed_action_ids, review.body.processed_action_ids); const status = await get("/status"); assert.equal(status.body.chain.ok, true); assert.ok(!status.body.receipts.some((r) => ["7R6QX8GZ3EW3S7PVJ9KQ6E2D4M::ingress", "email-review-responsibility::ingress"].includes(r.node)), "Brief/Review must not have phantom ingress receipts"); const devtools = spawnSync(path.join(prose, "node_modules/.bin/reactor-devtools"), [state, "--describe", "--json"], { cwd: project, env, encoding: "utf8", timeout: 30_000 }); assert.equal(devtools.status, 0, devtools.stderr); assert.equal(JSON.parse(devtools.stdout).chainVerify.ok, true); console.log(`#30 live review black box: five contracts, agent/human conflict, revision, confirmation, idempotency and restart verified; review-agent-cost=${JSON.stringify(reviewAgentReceipt.cost.tokens)}; no-send=true`);
})().catch(async (error) => { console.error(error); await diagnostics(); process.exitCode = 1; }).finally(async () => { await stop(workbench); await stop(daemon); if (process.env.KEEP_LIVE_FIXTURE) console.error(`#30 kept fixture: ${temp}`); else fs.rmSync(temp, { recursive: true, force: true }); });
